### ISSUE TITLE
Error with compartment analysis

### ISSUE THREAD

**Issue by mitchwjnorris** [markziemann/ART_methylation#11]
4: stop(gettextf("%s not meaningful for factors", sQuote(.Generic)))
3: Summary.factor(c(NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA), na.rm = FALSE) at meth_functions.R#274
2: compartment_enrichment(dma) at meth_functions.R#224
1: dm_analysis(samplesheet = samplesheet, sex = sex, groups = groups, 
       mx = Mval_flt, name = "top_nat_vs_ivf_inc", myann = myann, 
       beta = beta)

**Comment by markziemann** [comment]
Analysis barfs when there is only one type of compartment available in the dma object

**Comment by markziemann** [comment]
have increased the number of significant probes required before doing compartment analysis to 10. This should alleviate most problems
